web:
  build: .
  command: 'bash -c ''bundle exec rackup config.ru -p $PORT'''
  working_dir: /app/user
  environment:
    PORT: 8080
    REDISCLOUD_URL: 'redis://rediscloud:6379'
  ports:
    - '8080:8080'
  links:
    - rediscloud
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    REDISCLOUD_URL: 'redis://rediscloud:6379'
  ports:
    - '8080:8080'
  links:
    - rediscloud
  volumes:
    - '.:/app/user'
rediscloud:
  image: redis

